M48
; DRILL file {KiCad 7.0.8} date Mon Jan 29 14:08:55 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-29T14:08:55+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0935
%
G90
G05
T1
X4.8175Y-3.3437
X4.8175Y-3.5713
T2
X5.2574Y-3.6091
X5.2974Y-3.4091
X5.3374Y-3.6091
T3
X5.1974Y-3.4091
X5.1974Y-3.5341
X5.3974Y-3.4091
X5.3974Y-3.5341
T0
M30
