M48
; DRILL file {KiCad (6.0.8)} date Tue Aug 22 19:06:41 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-22T19:06:41+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X151.353Y-59.481
X151.353Y-64.481
T2
X111.43Y-59.46
X111.43Y-62.46
T3
X113.03Y-53.34
X113.03Y-85.09
X152.4Y-53.34
X152.4Y-85.09
T0
M30
