M48
; DRILL file {KiCad 7.0.8} date Sun Feb 18 15:21:39 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-18T15:21:39+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0512
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.1945Y-4.0785
X5.1945Y-4.2785
X6.51Y-4.056
X6.51Y-4.256
T2
X5.002Y-3.85
X5.002Y-4.492
X6.722Y-3.83
X6.726Y-4.48
T0
M30
