M48
; DRILL file {KiCad 7.0.8} date Mon Jan  1 18:02:11 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-01T18:02:11+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.300
%
G90
G05
T1
X131.941Y-103.594
X131.941Y-108.674
X167.64Y-103.429
X167.64Y-108.509
T0
M30
